import { Roboto } from 'next/font/google'
import { Adamina } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Header'

const roboto = Adamina({
  weight: '400',
  subsets: ['latin'],
})
 


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        {children}

        <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
        </body>
    </html>
  )
}
